name: CI/CD - Build and Deploy ValetsGo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y push imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            jcmedinanix/valetsgo-app:latest
            jcmedinanix/valetsgo-app:${{ github.sha }}

      - name: Deploy en VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/valetsgo-app
            docker-compose pull
            docker-compose up -d
            docker image prune -f
